### PR TITLE
jakubroztocil/rrule/issues/90 for meteor

### PR DESCRIPTION
**Pull request by paulbalomiri**
Hi,

Because i needed a fix for  [jakubroztocil/rrule/issues/90](https://github.com/jakubroztocil/rrule/issues/90) in a meteor project , I created a patch for rrule. This is the same change as [PR 92 on jakubroztocil/rrule](https://github.com/jakubroztocil/rrule/pull/92) applied to feature/meteor.

You could also wait to pull it from upstream, i just wanted to let you/everybody know that a fork with issue 90 solved is available for meteor.
- Merged the PR for this issue/bug [jakubroztocil/rrule/issues/90](https://github.com/jakubroztocil/rrule/issues/90) into feature/meteor branch
- bumped version to 2.1.1-dev according to changelog/discussion in the main package.

Cheers!
Paul

### CODE REVIEW

**Comment by aramk** [comment]
Awesome, thanks for that!

**Comment by aramk** [comment]
I also resolved a bunch of conflicts when merging `feature/timezone` into `feature/meteor`.

**Comment by paulbalomiri** [comment]
Thanks,

Where does timezone come from? Could tou add 4 lines to the ~~changelog~~ `Readme.md` mentioning the branches in your repo and what they stand for? I remember spending some time figuring it out.

If you want i could make this ticket. Thanks for maintaining this for the metor community!

**Comment by aramk** [comment]
Basically the time zone fixes I made address a limitation where all dates must be in the local time zone due to use of Date. See https://github.com/jakubroztocil/rrule/pull/97. Thanks for your contributions also.

**Pull request merged**
